# The docker-compose DSL syntax format we're using
version: "2.1"

services:

  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

  postgres:
    container_name: database
    build:
      context: "."
      dockerfile: "Dockerfile.postgres"
    restart: always
    ports:
      - "15432:5432"
    volumes:
      - .:/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3

  # An alias for common properties of multiple services
  node_base: &node_base
    container_name: node_base
    build: ./
    links:
      - "postgres"
      - "redis"
    volumes:
      - "./:/usr/src/app"
    environment:
      DB_HOST: postgres://postgres:password@postgres/primary_db
      TEST_DB_HOST: postgres://postgres:password@postgres/test_db
      REDIS_HOST: redis://cache
      REDIS_PORT: 6379

  # Run postgres migrations
  migration:
    <<: *node_base
    container_name: migration
    command: [ "npx", "knex", "migrate:latest" ]
    depends_on:
      postgres:
        condition: service_healthy

  # Run postgres seeding
  seed:
    <<: *node_base
    container_name: seed
    command: [ "npx", "knex", "seed:run", "--env", "development" ]
    depends_on:
      - migration

  # Primary Application Entrypoint
  webserver:
    <<: *node_base
    container_name: webserver
    ports:
      - "4000:4000"
      - "9229:9229"
    command: [ "npm", "run", "watch" ]
    depends_on:
      - migration
      - seed
