# The docker-compose DSL syntax format we're using
version: "2.1"

# The containers we want to start and the images to start
# them from
services:

  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

  postgres:
    container_name: database
    build:
      context: "."
      dockerfile: "Dockerfile.postgres"
    restart: always
    ports:
      - "15432:5432"
    volumes:
      - .:/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3

  node:
    container_name: webserver
    # the directory path - relative to this compose file - where
    # we'll be able to find the Dockerfile
    build: ./
    # the port mappings we do so that traffic that docker
    # will forward from localhost -> container
    ports:
      - "4000:4000"
      - "9229:9229"
    # tell docker compose to watch ./server.js - the path relative
    # to our compose file on our computer - and then make that reflect
    # the same file at /usr/src/app/server.js inside of the container
    volumes:
      - "./:/usr/src/app"
    links:
      - "postgres"
      - "redis"
    environment:
      DB_HOST: postgres://postgres:password@postgres/primary_db
      TEST_DB_HOST: postgres://postgres:password@postgres/test_db
      REDIS_HOST: redis://cache
      REDIS_PORT: 6379
    command: [ "npx", "knex", "migrate:latest" ]
    command: [ "npx", "knex", "seed:run", "--env", "development" ]
    command: [ "npm", "run", "watch" ]
    depends_on:
      - migration
      - seed

  migration:
    container_name: migration
    build: ./
    environment:
      DB_HOST: postgres://postgres:password@postgres/primary_db
      TEST_DB_HOST: postgres://postgres:password@postgres/test_d
    command: [ "npx", "knex", "migrate:latest" ]
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - "postgres"
    volumes:
      - "./:/usr/src/app"

  seed:
    container_name: seed
    build: ./
    environment:
      DB_HOST: postgres://postgres:password@postgres/primary_db
      TEST_DB_HOST: postgres://postgres:password@postgres/test_d
    command: [ "npx", "knex", "seed:run", "--env", "development" ]
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - "postgres"
    volumes:
      - "./:/usr/src/app"
